version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - test:
          name: test-3.6
          version: "3.6"
      - test:
          name: test-3.7
          version: "3.7"
          requires:
            - test-3.6
      - build:
          requires:
            - test-3.6
            - test-3.7
      - deploy:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
jobs:
  test:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: circleci/python:<< parameters.version >>
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "Pipfile.lock" }}
      - run:
          name: install python dependencies
          command: |
            python<< parameters.version >> -m venv ~/venv
            . ~/venv/bin/activate
            make dev
      - save_cache:
          key: v1-dependency-cache-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/venv"
      - run:
          name: run tests
          command: |
            . ~/venv/bin/activate
            make test
            pip install .
            codecov
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "Pipfile.lock" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            make dev
      - save_cache:
          key: v1-dependency-cache-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/venv"
      - run:
          name: generate coverage and package data
          command: |
            . ~/venv/bin/activate
            make test
            make coverage
            make package
      - persist_to_workspace:
          root: "~"
          paths:
            - venv
            - project/dist
  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - attach_workspace:
          at: "~"
      - run:
          name: verify git tag vs. version
          command: |
            [[ "$CIRCLE_TAG" == "$(python -c 'from flake8_fixme.version import version; print(version)')" ]]
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: upload to pypi
          command: |
            . ~/venv/bin/activate
            make upload
