version: 2.1
workflows:
  build_and_deploy:
    jobs:
      # First test triggered by a commit
      - test:
          name: test-3.6
          tag: "3.6"
          version: "3.6"
          # required as deploy has tags version filter
          filters:
            tags:
              only: /.*/
      # Other test environments in parallel
      - test:
          name: test-3.7
          tag: "3.7"
          version: "3.7"
          requires:
            - test-3.6
          filters:
            tags:
              only: /.*/
      - test:
          name: test-3.8
          tag: "rc"
          version: "3.8"
          requires:
            - test-3.6
          filters:
            tags:
              only: /.*/
      # Build packages
      - build:
          requires:
            - test-3.6
            - test-3.7
            - test-3.8
          filters:
            tags:
              only: /.*/
      # Deploy if tagged
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
jobs:
  test:
    parameters:
      tag:
        type: string
      version:
        type: string
    docker:
      - image: circleci/python:<< parameters.tag >>
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "Pipfile.lock" }}
      - run:
          name: install python dependencies
          command: |
            python<< parameters.version >> -m venv ~/venv
            . ~/venv/bin/activate
            make dev
      - save_cache:
          key: v1-dependency-cache-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/venv"
      - run:
          name: run tests
          command: |
            . ~/venv/bin/activate
            make test
            pip install .
            codecov
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "Pipfile.lock" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            make dev
      - save_cache:
          key: v1-dependency-cache-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/venv"
      - run:
          name: generate coverage and package data
          command: |
            . ~/venv/bin/activate
            make test
            make coverage
            make package
      - persist_to_workspace:
          root: "~"
          paths:
            - venv
            - project/dist
  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - attach_workspace:
          at: "~"
      - run:
          name: verify git tag vs. version
          command: |
            [[ "$CIRCLE_TAG" == "v$(python -c 'from flake8_fixme.metadata import VERSION; print(VERSION)')" ]]
      - run:
          name: upload to pypi
          command: |
            . ~/venv/bin/activate
            make upload
